1. Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [72]:
import numpy as np

In [49]:
a = np.array([[1,2,3,3,1],[6,8,11,10,7]]).transpose()

In [50]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [51]:
np.shape(a)

(5, 2)

In [52]:
mean_a = np.mean(a, axis = 0)

In [74]:
mean_a

array([2. , 8.4])

2. Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [65]:
a_centered = a - mean_a

In [54]:
a_centered = np.vstack((mean_a,mean_a,mean_a,mean_a,mean_a))

In [66]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [76]:
np.shape(a_centered)

(5, 2)

3. Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [75]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [77]:
a_centered_sp

8.0

In [78]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

4. Число, которое мы получили в конце задания 3 является ковариацией двух признаков, 
содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, 
поэтому полученная нами величина является несмещенной оценкой ковариации.

In [79]:
np.cov(a.T)[0, 1]

2.0